Ejercicios matrices Daniel Conrado Monroy Madrid 16012674


In [2]:
import numpy as np



**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresion.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = numero de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [3]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

b1=gamma*P
b2=np.matmul(b1,V)
bellman=b2+R

print(bellman)



[10.  2.  5.]


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [61]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    return 1/(1+np.exp(-x))

def relu(x):
    return np.maximum(0,x)

def neural_network(x):
    hiddenl=np.array([[0.712,0.355,0.268],[0.112,0.855,0.468]])
    output=np.array([[0.116],[0.329],[0.708]])
    o1=np.matmul(x,hiddenl)
    o1=sigmoid(o1)
    o2=np.matmul(o1,output)
    o3=sigmoid(o2)
    o4=relu(o2)
    
    
    return o2,o3,o4

x=np.array([[1,1]])

print(neural_network(x))  #En la respuesta se imprime el resultado de la operación matricial como tal, el resultado aplicando sigmoid (como aparece en la imagen) y también se incluye el resultado aplicando reLU. 

(array([[0.81275154]]), array([[0.69269553]]), array([[0.81275154]]))


In [60]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

print(neural_network(x=X))

(array([[0.85897151],
       [0.6748703 ],
       [1.14904686],
       [1.15125178],
       [1.14187076],
       [0.72619803],
       [1.15019715],
       [1.153     ],
       [1.1500904 ],
       [1.153     ]]), array([[0.70244573],
       [0.66259284],
       [0.75933678],
       [0.75973948],
       [0.75802295],
       [0.6739704 ],
       [0.75954693],
       [0.76005845],
       [0.75952743],
       [0.76005845]]), array([[0.85897151],
       [0.6748703 ],
       [1.14904686],
       [1.15125178],
       [1.14187076],
       [0.72619803],
       [1.15019715],
       [1.153     ],
       [1.1500904 ],
       [1.153     ]]))
