Tarea diferencia entre np.array y np.matrix - Daniel Conrado Monroy Madrid 16012674

La diferencia radica en que el array es de N dimensiones, mientras que la matriz es bidimensional. Por otro lado, al utilizar np.matriz la operación de multiplicación es identificada por python como la multiplicación matricial que se estudia en álgebra lineal, mientras que al ultilizar arrays para obtener la multiplicación tendría que ejecutarse la operación de producto punto ya que al tratarse de arrays se opera elemento por elemento (element-wise) y por lo tanto, no se obtiene la operación deseada(multiplicación matricial). Un ejemplo ayudará a clarificar lo arriba explicado:

In [1]:
import numpy as np

In [7]:
a=np.matrix('5 6;2 3')
b=np.matrix('1 2;7 8')
print(a*b) #En este caso, el resultado muestra la operación típica de multiplicación de matrices.


[[47 58]
 [23 28]]


In [9]:
#¿Qué pasa si se realiza la misma operación con np.array? 
c=np.array([[5, 6], [2, 3]])
d=np.array([[1, 2], [7, 8]])
print(a*b) #Como se puede observar en el resultado, no resulta en la misma respuesta ya que lo que hizo fue multiplicar elemento por elemento (5x1,6x2,2x7 y 3x8)

[[ 5 12]
 [14 24]]


In [11]:
#En el caso de los arrays, la operación a ejecutar sería el producto punto, el cual sí devolverá el resultado del principio (la multiplicación matricial)
c=np.array([[5, 6], [2, 3]])
d=np.array([[1, 2], [7, 8]])
print(np.dot(c,d))

[[47 58]
 [23 28]]


Como se puede observar, la operación producto punto sí devuelve el resultado deseado.

Otra operación que actúa de manera distinta es la de elevar a determinada potencia. Cuando es una matriz (a**2) realiza la operación de a * a. Sin embargo, cuando es un array, de nuevo, python realiza la operación elemento por elemento; es decir, cada elemento del array "a" lo eleva al cuadrado. El ejemplo ayudará a clarificar esto:

In [12]:
a=np.matrix('5 6;2 3')
print(a**2)

[[37 48]
 [16 21]]


In [13]:
c=np.array([[5, 6], [2, 3]])
print(c**2)

[[25 36]
 [ 4  9]]


En el primer caso, realizó la operación de la matriz multiplicada por la matriz (a * a); en el segundo tomó cada elemento del array y lo elevó al cuadrado (5 ** 2,6 * *2,2 ** 2,3 ** 3)